name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Check
      run: |
        npm install
        gulp build
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Settings > Secret 建立的 ACCESS_TOKEN
        branch: gh-pages # deploy 到 gh-pages 這個分支
        folder: dist # build 後的資料夾
